### ISSUE TITLE
Unable to select first recipe in the list in cooking menu

### ISSUE THREAD

**Issue by alhails** [egocarib/CavesOfQud-QudUX-v2#27]
First of all - thanks for the amazing mod.  I'm running client version 2.0.206.57.  I have noticed that I am unable to select the first recipe on the cooking menu.  It just returns me to the campfire menu, but doesn't cook the meal.  If I add another recipe which pushes the previous one down the list, then it works fine from position two in the list.

I'm running the following mods...
QudUX 2.0
You see a cave spider and that's ok 1.0.1
Colors of Qud 1.3

Let me know if you need any more information or need be to try anything

**Comment by egocarib** [comment]
Fixed in f0dbc55c79e9010df29bb11cc5bd4a757b00c2f6. Thank you for the report!
