### ISSUE TITLE
Weird Issue

### ISSUE THREAD

**Issue by GPeckman** [egocarib/CavesOfQud-QudUX-v2#6]
I recently attempted to use this mod, but I've encountered a strange issue. I was able to activate the mod just fine. The game ran, and I could see the new options added by QudUX in the options menu. However, the mod did not seem to be doing anything. Every option was enabled (except for the one that disables magnets), but none of the UIs were different. I also never saw any option to ask traders when they were going to restock.

Thoughts?

[Player.log](https://github.com/egocarib/CavesOfQud-QudUX-v2/files/5953059/Player.log)
[build_log.txt](https://github.com/egocarib/CavesOfQud-QudUX-v2/files/5953060/build_log.txt)
[game_log.txt](https://github.com/egocarib/CavesOfQud-QudUX-v2/files/5953061/game_log.txt)

**Comment by oschwab** [comment]
According to the log file, QudUX crashes silently.
You are using version  2.0.201.47 , which is a bit outdated (october 2020).
Maybe try to update to latest one.

**Comment by GPeckman** [comment]
Updating seems to have fixed it. Thank you very much.
